# --- Build stage ---
FROM oven/bun:latest AS build

WORKDIR /app

# Accept build arguments
ARG MODE
ARG API
ARG APL_KEY_ID
ARG APL_TEAM_ID
ARG APL_APP_ID
ARG APL_MAPKIT_SNAPSHOT_TOKEN
ARG MAPKIT_ORIGIN
ARG MAPKIT_KEY

ARG FB_API_KEY
ARG FB_AUTH_DOMAIN
ARG FB_PROJECT_ID
ARG FB_STORAGE_BUCKET
ARG FB_MESSAGING_SENDER_ID
ARG FB_APP_ID
ARG FB_MEASUREMENT_ID

ARG DSN

ARG SENTRY_PROJECT
ARG SENTRY_ORG
ARG SENTRY_AUTH_TOKEN

# Set environment variables for the Nuxt build
ENV MODE=${MODE}
ENV API=${API}
ENV APL_KEY_ID=${APL_KEY_ID}
ENV APL_TEAM_ID=${APL_TEAM_ID}
ENV APL_APP_ID=${APL_APP_ID}
ENV APL_MAPKIT_SNAPSHOT_TOKEN=${APL_MAPKIT_SNAPSHOT_TOKEN}
ENV MAPKIT_ORIGIN=${MAPKIT_ORIGIN}
ENV MAPKIT_KEY=${MAPKIT_KEY}

ENV FB_API_KEY=${FB_API_KEY}
ENV FB_AUTH_DOMAIN=${FB_AUTH_DOMAIN}
ENV FB_PROJECT_ID=${FB_PROJECT_ID}
ENV FB_STORAGE_BUCKET=${FB_STORAGE_BUCKET}
ENV FB_MESSAGING_SENDER_ID=${FB_MESSAGING_SENDER_ID}
ENV FB_APP_ID=${FB_APP_ID}
ENV FB_MEASUREMENT_ID=${FB_MEASUREMENT_ID}

ENV DSN=${DSN}

ENV SENTRY_PROJECT=${SENTRY_PROJECT}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}

# Install dependencies
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

# Build the application
COPY . .
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN bun run build

# --- Runtime stage (only the built output, no node_modules or source) ---
FROM oven/bun:latest

WORKDIR /app

COPY --from=build /app/.output .output

EXPOSE 80

ENV NODE_ENV=production
ENV NITRO_HOST=0.0.0.0
ENV NITRO_PORT=80

CMD ["bun", ".output/server/index.mjs"]
